blueprint:
  name: Notify when motion detected
  description: Sends a notification when motion is detected by any of the listed sensors.
  domain: automation
  input:
    motion_sensors:
      name: Motion sensors
      description: The sensors that will trigger the notification.
      selector:
        target:
          entity:
            domain: binary_sensor
            device_class: motion
    notify_device:
      name: Device
      description: The mobile device to notify.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: state
  entity_id: !input 'motion_sensors'
  from: 'off'
  to: 'on'

action:
  service: notify.notify
  data:
    message: >
      Motion detected by {{ trigger.to_state.name }}
    target: !input 'notify_device'